#!/usr/bin/env python3
"""Orchestrator: query -> multi-backend fetch -> ranked snippets -> note file.

Calls wiki.py, fetch.py (DDG), arxiv.py, crossref.py as subprocesses.
Stdlib only. Auto-detects output language from query.

Default output: <cwd>/.feynman-searchs/research-<slug>.md
If <cwd> is a git repo, .feynman-searchs/ is auto-added to .gitignore.
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import time
import unicodedata
from pathlib import Path

HERE = Path(__file__).resolve().parent


def detect_lang(q: str) -> str:
    pt_signal = re.search(
        r"\b(o que|como|por que|qual|quem|onde|pesquisar|explique|leigo|aluno)\b",
        q.lower(),
    )
    return "pt" if pt_signal else "en"


def slug(s: str) -> str:
    """ASCII-only kebab-case slug. Strips accents (NFKD) before regex."""
    s = unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode("ascii")
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")[:60]


def ensure_gitignore_line(repo_root: Path, line: str) -> bool:
    """If repo_root is a git repo, append `line` to .gitignore (idempotent).
    Returns True iff the line was added now."""
    if not (repo_root / ".git").exists():
        return False
    gi = repo_root / ".gitignore"
    existing = gi.read_text() if gi.exists() else ""
    if any(l.strip() == line for l in existing.splitlines()):
        return False
    with gi.open("a") as f:
        if existing and not existing.endswith("\n"):
            f.write("\n")
        f.write(line + "\n")
    return True


def default_out_path(query: str) -> tuple[Path, bool]:
    """Compute default output path under <cwd>/.feynman-searchs/.
    Returns (path, gitignore_added)."""
    cwd = Path.cwd()
    out_dir = cwd / ".feynman-searchs"
    out_dir.mkdir(parents=True, exist_ok=True)
    gi_added = ensure_gitignore_line(cwd, ".feynman-searchs/")
    return out_dir / f"research-{slug(query)}.md", gi_added


def call(script: str, *args: str) -> dict:
    cmd = [sys.executable, str(HERE / script), *args]
    try:
        out = subprocess.run(cmd, capture_output=True, text=True, timeout=15, check=False)
        if out.returncode != 0:
            return {"error": (out.stderr.strip() or f"{script} exit {out.returncode}")[:300]}
        return json.loads(out.stdout) if out.stdout.strip() else {"error": "empty output"}
    except subprocess.TimeoutExpired:
        return {"error": f"{script} timed out"}
    except json.JSONDecodeError as e:
        return {"error": f"{script} returned non-JSON: {e}"}


def render_note(query: str, lang: str, results: dict) -> str:
    L = []
    L += [f"# {query}", "", f"_Language: {lang} · Generated by feynman-search_", ""]
    L += ["## TL;DR (3 lines)", "", "_Fill in: 3 lines, plain language._", ""]

    wiki = results.get("wiki", {})
    if wiki.get("extract"):
        L += ["## Wikipedia summary", "", wiki["extract"], "", f"<{wiki.get('url','')}>", ""]

    ddg = results.get("ddg", {})
    if ddg.get("results"):
        L += ["## Web results (DuckDuckGo)", ""]
        for r in ddg["results"][:5]:
            L.append(f"- [{r['title']}]({r['url']})")
        L.append("")

    arxiv = results.get("arxiv", {})
    if arxiv.get("papers"):
        L += ["## arXiv abstracts", ""]
        for p in arxiv["papers"][:3]:
            authors = ", ".join(p.get("authors", [])[:3])
            L += [f"### {p['title']}", "", f"_{authors}_", "", p.get("summary", ""), "", f"<{p.get('url','')}>", ""]

    cr = results.get("crossref", {})
    if cr.get("works"):
        L += ["## Crossref papers", ""]
        for w in cr["works"][:5]:
            L.append(
                f"- {w.get('title','?')} ({w.get('year','?')}) — DOI: {w.get('doi','?')}"
            )
        L.append("")

    L += [
        "## Feynman synthesis",
        "",
        "### 1. Plain-language explanation",
        "_Analogy a 12-year-old would get._",
        "",
        "### 2. Technical depth",
        "_What's actually going on, with the precise terms._",
        "",
        "### 3. Open questions and gaps",
        "_Where the explanation breaks down or sources disagree._",
        "",
    ]
    return "\n".join(L)


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("query", help="Query string (English recommended for best coverage)")
    p.add_argument("--backends", default="wiki,ddg",
                   help="Comma-separated: wiki,ddg,arxiv,crossref")
    p.add_argument("--max-results", type=int, default=5)
    p.add_argument("--lang", default="auto",
                   help="Wikipedia language: en|pt|auto (auto detects from query)")
    p.add_argument("--out", default="",
                   help="Output path (default: <cwd>/.feynman-searchs/research-<slug>.md)")
    args = p.parse_args()

    lang = detect_lang(args.query) if args.lang == "auto" else args.lang
    backends = [b.strip() for b in args.backends.split(",") if b.strip()]
    results: dict = {}

    for b in backends:
        if b == "wiki":
            results["wiki"] = call("wiki.py", args.query, "--lang", lang)
        elif b == "ddg":
            results["ddg"] = call("fetch.py", "ddg", args.query, "--max", str(args.max_results))
        elif b == "arxiv":
            results["arxiv"] = call("arxiv.py", args.query, "--max", str(args.max_results))
            time.sleep(3)  # arXiv courtesy
        elif b == "crossref":
            results["crossref"] = call("crossref.py", args.query, "--max", str(args.max_results))

    note = render_note(args.query, lang, results)
    if args.out:
        out_path = Path(args.out)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        gi_added = False
    else:
        out_path, gi_added = default_out_path(args.query)
    out_path.write_text(note, encoding="utf-8")

    summary = {
        "path": str(out_path),
        "lang": lang,
        "backends_called": list(results.keys()),
        "wiki_extract": results.get("wiki", {}).get("extract", "")[:300],
        "errors": {k: v["error"] for k, v in results.items() if isinstance(v, dict) and "error" in v},
        "gitignore_updated": gi_added,
    }
    print(json.dumps(summary, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
